default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: biblio
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  schema_search_path: public

test:
  <<: *default
  database: biblio

production:
  <<: *default
  database: biblio
  username: postgres
  password: postgres
